name: Do checks

# Run when there's an update
on:
  push:

# This job runs pybryt on the notebook and then pushes an issue/PR
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submission
      uses: actions/checkout@v2
      with:
        path: main

    #- name: Checkout reference
    #  uses: actions/checkout@v2
    #  with:
    #    repository: ic-acse/pybryt-reference
    #    token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
    #    path: reference
      
    # Install Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # Install dependencies
    - name: Install dependencies
      run: |
          pip install pybryt torch matplotlib sklearn --user
    - name: Run tests
      run: |
          PYTHONPATH=$PWD/main python3 main/.github/checks.py main/Afternoon_Session_2_Diving_into_Optimization_and_Neural_Nets_Exercise_1.ipynb main/.github/solution.pkl report.md

    # Update Issue
    - name: Update Issue
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: result.md
        update_existing: true
